-- C module migration: base business tables for the trade domain (14 tables).
-- Target: isolated dev database (e.g. ruoyi_dev_c_test). Do NOT run on shared DB without approval.
-- Safe to re-run: every table uses CREATE TABLE IF NOT EXISTS (no DROP, no data loss).
-- Must run BEFORE the other c/ migrations: C_20260928_003 alters sys_order,
-- C_20260928_006 alters sys_work; both require the tables created here.
-- No library/schema prefix on purpose, so the file is portable across DB instances.

CREATE TABLE IF NOT EXISTS `sys_business_follow` (
  `follow_id` bigint NOT NULL AUTO_INCREMENT,
  `partner_id` bigint NOT NULL,
  `follower_id` bigint NOT NULL,
  `follow_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `content` text COLLATE utf8mb4_general_ci NOT NULL,
  `next_follow_date` date DEFAULT NULL,
  `next_follow_content` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `follow_time` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`follow_id`),
  KEY `idx_partner_id` (`partner_id`) USING BTREE,
  KEY `idx_follower_id` (`follower_id`) USING BTREE,
  KEY `idx_follow_time` (`follow_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_chat_message` (
  `message_id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` bigint NOT NULL,
  `sender_id` bigint NOT NULL,
  `receiver_id` bigint NOT NULL,
  `msg_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `content` text COLLATE utf8mb4_general_ci NOT NULL,
  `file_url` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `is_read` tinyint NOT NULL,
  `read_time` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`message_id`),
  KEY `idx_session_id` (`session_id`) USING BTREE,
  KEY `idx_sender_id` (`sender_id`) USING BTREE,
  KEY `idx_created_at` (`created_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_chat_session` (
  `session_id` bigint NOT NULL AUTO_INCREMENT,
  `session_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `inquiry_id` bigint DEFAULT NULL,
  `user1_id` bigint NOT NULL,
  `user2_id` bigint NOT NULL,
  `last_message` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `last_message_time` datetime DEFAULT NULL,
  `user1_unread` int NOT NULL,
  `user2_unread` int NOT NULL,
  `status` tinyint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`session_id`),
  UNIQUE KEY `uk_user1_user2` (`user1_id`,`user2_id`) USING BTREE,
  KEY `idx_last_message_time` (`last_message_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_contact_profile` (
  `contact_id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `phone_cipher` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `email_cipher` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `wechat_cipher` varchar(256) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `display_scope` varchar(30) COLLATE utf8mb4_general_ci NOT NULL,
  `display_status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `verify_status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `updated_by` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`contact_id`),
  UNIQUE KEY `uk_owner_id` (`owner_id`) USING BTREE,
  KEY `idx_display_scope` (`display_scope`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `sys_demand` (
  `demand_id` bigint NOT NULL AUTO_INCREMENT,
  `demand_no` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `client_id` bigint NOT NULL,
  `title` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `genre_id` int NOT NULL,
  `budget` decimal(12,2) NOT NULL,
  `deadline` date NOT NULL,
  `requirement` text COLLATE utf8mb4_general_ci NOT NULL,
  `contact_info` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `submission_count` int NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`demand_id`),
  UNIQUE KEY `uk_demand_no` (`demand_no`) USING BTREE,
  KEY `idx_client_id` (`client_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_demand_submission` (
  `submission_id` bigint NOT NULL AUTO_INCREMENT,
  `demand_id` bigint NOT NULL,
  `work_id` bigint NOT NULL,
  `submitter_id` bigint NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `submit_message` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `review_remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`submission_id`),
  UNIQUE KEY `uk_demand_work` (`demand_id`,`work_id`) USING BTREE,
  KEY `idx_demand` (`demand_id`) USING BTREE,
  KEY `idx_submitter` (`submitter_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_inquiry` (
  `inquiry_id` bigint NOT NULL AUTO_INCREMENT,
  `inquiry_no` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `work_id` bigint NOT NULL,
  `buyer_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  `license_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `intended_use` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `budget` decimal(12,2) DEFAULT NULL,
  `message` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `expire_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`inquiry_id`),
  UNIQUE KEY `uk_inquiry_no` (`inquiry_no`) USING BTREE,
  KEY `idx_buyer_id` (`buyer_id`) USING BTREE,
  KEY `idx_seller_id` (`seller_id`) USING BTREE,
  KEY `idx_work_id` (`work_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_offline_cooperation` (
  `cooperation_id` bigint NOT NULL AUTO_INCREMENT,
  `cooperation_no` varchar(64) COLLATE utf8mb4_general_ci NOT NULL,
  `work_id` bigint NOT NULL,
  `creator_id` bigint NOT NULL,
  `partner_id` bigint DEFAULT NULL,
  `contact_id` bigint DEFAULT NULL,
  `source` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `expected_amount` decimal(14,2) DEFAULT NULL,
  `next_follow_at` datetime DEFAULT NULL,
  `last_follow_at` datetime DEFAULT NULL,
  `remark` varchar(1000) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `operator_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`cooperation_id`),
  UNIQUE KEY `uk_cooperation_no` (`cooperation_no`) USING BTREE,
  KEY `idx_work_status` (`work_id`) USING BTREE,
  KEY `idx_creator_id` (`creator_id`) USING BTREE,
  KEY `idx_next_follow` (`next_follow_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `sys_order` (
  `order_id` bigint NOT NULL AUTO_INCREMENT,
  `order_no` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `contract_id` bigint DEFAULT NULL,
  `escrow_id` bigint DEFAULT NULL,
  `inquiry_id` bigint DEFAULT NULL,
  `quote_id` bigint DEFAULT NULL,
  `work_id` bigint NOT NULL,
  `buyer_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  `order_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `license_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `total_amount` decimal(12,2) NOT NULL,
  `platform_fee` decimal(12,2) NOT NULL,
  `split_rate` decimal(5,4) NOT NULL,
  `seller_amount` decimal(12,2) NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `pay_time` datetime DEFAULT NULL,
  `complete_time` datetime DEFAULT NULL,
  `ext_json` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `uk_order_no` (`order_no`) USING BTREE,
  KEY `idx_buyer_id` (`buyer_id`) USING BTREE,
  KEY `idx_seller_id` (`seller_id`) USING BTREE,
  KEY `idx_work_id` (`work_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE,
  KEY `idx_created_at` (`created_at`) USING BTREE,
  KEY `idx_pay_time` (`pay_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_order_status_log` (
  `log_id` bigint NOT NULL AUTO_INCREMENT,
  `order_id` bigint NOT NULL,
  `from_status` varchar(30) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `to_status` varchar(30) COLLATE utf8mb4_general_ci NOT NULL,
  `operator_id` bigint DEFAULT NULL,
  `operator_role` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  KEY `idx_order` (`order_id`) USING BTREE,
  KEY `idx_to_status` (`to_status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_partner` (
  `partner_id` bigint NOT NULL AUTO_INCREMENT,
  `partner_no` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `partner_name` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `partner_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `contact_person` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `contact_phone` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `contact_email` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `demand_tags` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `cooperation_count` int NOT NULL,
  `total_amount` decimal(14,2) NOT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `remark` text COLLATE utf8mb4_general_ci,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`partner_id`),
  UNIQUE KEY `uk_partner_no` (`partner_no`) USING BTREE,
  KEY `idx_partner_type` (`partner_type`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_quote` (
  `quote_id` bigint NOT NULL AUTO_INCREMENT,
  `quote_no` varchar(32) COLLATE utf8mb4_general_ci NOT NULL,
  `inquiry_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  `quoter_id` bigint NOT NULL,
  `quoter_role` varchar(10) COLLATE utf8mb4_general_ci NOT NULL,
  `price` decimal(12,2) NOT NULL,
  `license_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `valid_days` int NOT NULL,
  `description` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `expire_at` datetime NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`quote_id`),
  UNIQUE KEY `uk_quote_no` (`quote_no`) USING BTREE,
  KEY `idx_inquiry_id` (`inquiry_id`) USING BTREE,
  KEY `idx_inquiry_role` (`inquiry_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_selection` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `client_id` bigint NOT NULL,
  `work_id` bigint NOT NULL,
  `selection_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `demand_id` bigint DEFAULT NULL,
  `remark` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_client_work_type` (`client_id`,`work_id`,`selection_type`) USING BTREE,
  KEY `idx_client_id` (`client_id`) USING BTREE,
  KEY `idx_work_id` (`work_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `sys_work` (
  `work_id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `cover` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `author_id` bigint NOT NULL,
  `genre_id` int NOT NULL,
  `work_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `upload_type` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `length_type` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `summary` text COLLATE utf8mb4_general_ci,
  `core_setting` text COLLATE utf8mb4_general_ci,
  `character_setting` text COLLATE utf8mb4_general_ci,
  `price` decimal(12,2) NOT NULL,
  `trade_type` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `trade_enabled` tinyint NOT NULL,
  `negotiable_min` decimal(12,2) DEFAULT NULL,
  `negotiable_max` decimal(12,2) DEFAULT NULL,
  `quote_valid_days` int NOT NULL,
  `word_count` int NOT NULL,
  `episode_count` int DEFAULT NULL,
  `duration` int DEFAULT NULL,
  `is_free` tinyint NOT NULL,
  `preview_enabled` tinyint DEFAULT NULL,
  `preview_episodes` int DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `is_copyrighted` tinyint NOT NULL,
  `view_count` int NOT NULL,
  `favorite_count` int NOT NULL,
  `sale_count` int NOT NULL,
  `rating` decimal(3,1) NOT NULL,
  `quality_level` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `reviewer_id` bigint DEFAULT NULL,
  `review_time` datetime DEFAULT NULL,
  `reject_reason` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `ext_json` json DEFAULT NULL,
  `is_deleted` tinyint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `update_by` varchar(64) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `remark` varchar(500) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`work_id`),
  KEY `idx_author_id` (`author_id`) USING BTREE,
  KEY `idx_genre_id` (`genre_id`) USING BTREE,
  KEY `idx_status` (`status`) USING BTREE,
  KEY `idx_work_type` (`work_type`) USING BTREE,
  KEY `idx_created_at` (`created_at`) USING BTREE,
  KEY `idx_view_count` (`view_count`) USING BTREE,
  KEY `idx_price` (`price`) USING BTREE,
  KEY `idx_trade_enabled` (`trade_enabled`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Evidence: how many of the 14 C trade tables now exist in this schema.
SELECT COUNT(*) AS c_trade_table_count
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN (
    'sys_business_follow','sys_chat_message','sys_chat_session','sys_contact_profile',
    'sys_demand','sys_demand_submission','sys_inquiry','sys_offline_cooperation',
    'sys_order','sys_order_status_log','sys_partner','sys_quote','sys_selection','sys_work'
  );
